---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Configuring Dependabot for a Python project
# https://til.simonwillison.net/github/dependabot-python-setup

version: 2
updates:
  # BUG: Dependabot couldn't fetch path-based dependencies (pip)
  # https://github.com/dependabot/dependabot-core/issues/9554
  - package-ecosystem: "pip"
    # Specify the root directories
    directories:
      - "/"
      - "*"  # The location of manifest files using the wildcard character
      - "**/*"  # All directories from the current layer and below recursively
      - "**"
      - "*/**"
      - "**/"
      - "*/*"
      - "**/**"
    schedule:
      interval: "daily"
    # Labels on pull requests for version updates only
    labels:
      - 'pip'
      - "pip dependencies"
      - "dependencies"
  # Enable version updates for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    # Labels on pull requests for version updates only
    labels:
      - "GitHub actions versions"
