name: Codecov Workflow
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
    secrets:
      codecov_token:
        required: true
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.x" ]
    steps:
    - uses: actions/checkout@main
    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Generate coverage report
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.4.1
      with:
        token: ${{ secrets.codecov_token }}
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
        attempt_limit: 5
        attempt_delay: 30000