---
name: CodeClimate Coverage Report

on:
  workflow_call:
    secrets:
      qlty_reporter_id:  # Updated secret name for Qlty
        required: true

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install pytest pytest-cov
      - name: Check pytest version
        run: |
          python -m pytest --version
      - name: Check PYTHONPATH
        run: |
          pwd
          export PYTHONPATH=.:$PYTHONPATH
      - name: Run Tests and Generate Coverage
        run: |
          python -m pytest tests/ -v --cov-report term-missing --cov=lessons --cov-report=xml
      - name: Verify Coverage Report
        run: |
          ls -l coverage.xml
          cat coverage.xml
      - name: Upload Coverage to Qlty
        uses: qlty/code-coverage-action@latest  # Replace with actual Qlty action
        env:
          QLTY_REPORTER_ID: ${{ secrets.qlty_reporter_id }}  # Replace with actual env variable
        with:
          coverageFiles: coverage.xml
          format: cobertura  # Assuming Cobertura XML is supported
          debug: true