name: 'Markdown Lint'

on:
  pull_request:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      
      # lint markdown
      - uses: actions/setup-node@master
      - name: "Lint Markdown"
        run: |
          npm install -g markdownlint-cli
          markdownlint '**.md' --ignore node_modules --disable MD013
