---
name: 'Markdown Lint'

on:  # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          fix: true
          globs: '**/*.md'
