---
name: 'Markdown Lint'

on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          fix: true
          globs: '**/*.md'
