---
name: Qlty Coverage Report

on:  # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      qlty_reporter_id:
        required: true

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@main
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install pytest pytest-cov
      - name: Check pytest version
        run: |
          python -m pytest --version
      - name: Check PYTHONPATH
        run: |
          pwd
          export PYTHONPATH=.:$PYTHONPATH
      - name: Check Runner Architecture
        run: uname -m
      - name: Install Qlty CLI
        # yamllint disable rule:line-length
        run: |
          curl https://qlty.sh | sh || echo "Failed to download Qlty CLI tarball"
          qlty init
          qlty --version || echo "Qlty CLI not installed correctly"
      - name: Run Tests and Generate Coverage
        # yamllint disable rule:line-length
        run: |
          python -m pytest tests/ -v --cov-report term-missing --cov=lessons --cov-report=xml
      - name: Verify Coverage Report
        run: |
          ls -l coverage.xml
          cat coverage.xml
      - name: Upload Coverage to Qlty
        env:
          QLTY_COVERAGE_TOKEN: ${{ secrets.qlty_reporter_id }}
        run: |
          qlty coverage publish --format cobertura coverage.xml --debug
