---
name: RST Lint

on:  # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        # This is the version of the action for setting up Python,
        # not the Python version.
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: Install RST Lint
        run: |
          python -m pip install restructuredtext_lint
      - name: Check RST Lint Version
        run: |
          rst-lint --version
      - name: Lint RST files
        run: |
          rst-lint docs
