name: "Snyk for a new build"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
    secrets:
      snyk_token:
        description: 'A Snyk token passed from the caller workflow'
        required: true
jobs:
  security:
    permissions:
      contents: read         # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read          # only required for a private repository by
                             # github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
        # Source: https://github.com/actions/setup-python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true
      - name: Install python prerequisites
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      # If you want to send data to Snyk, and be alerted when new
      # vulnerabilities are discovered, you can run Snyk monitor like so:
      - name: Run Snyk to send data to Snyk
        run: |
          snyk monitor
        env:
          token: ${{ secrets.snyk_token }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk to check for vulnerabilities and fix them
        run: |
          python -m pip show setuptools
          snyk fix
          snyk test --sarif-file-output=snyk.sarif --file=requirements.txt --package-manager=pip --skip-unresolved
        env:
          token: ${{ secrets.snyk_token }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true # To make sure that SARIF upload gets called
        # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif