# The Snyk Action will fail when vulnerabilities are found.
# This would prevent the SARIF upload action from running,
# so we need to introduce a continue-on-error option.
# SOURCE: https://github.com/snyk/actions/tree/master/python-3.10
# https://github.com/ikostan/pico/new/master?filename=.github%2Fworkflows%2Fsnyk-security.yml&workflow_template=code-scanning%2Fsnyk-security

name: "Snyk for a new build"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
    secrets:
      snyk_token:
        description: 'A Snyk token passed from the caller workflow'
        required: true
jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by
                    # github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest
          pip install -r requirements.txt

      - name: Check to make sure that the module is in your Python path
        run: |
          echo $PYTHONPATH
          python --version

      - name: Install Snyk with standalone executables
        run: |
          curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/

      - name: Check which version of the Snyk CLI you have installed by running
        run:
          snyk --version

      - name: The snyk auth command authenticates your machine to associate the Snyk CLI with your Snyk account.
        run: |
          echo "$snyk_token"
          echo "$SNYK_TOKEN"
          snyk auth SNYK_TOKEN
          snyk auth snyk_token

      - name: Snyk Code test
        run: |
          snyk test --all-projects -d
        # snyk code test --sarif  > results.sarif -d
        continue-on-error: true

        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
      - name: Snyk Open Source monitor
        run:
          snyk monitor --all-projects
        continue-on-error: true

        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
        # Use || true to not fail the pipeline.
      - name: Snyk IaC test and report
        run:
          snyk iac test --report  # || true
        continue-on-error: true

        # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
