---
# https://coderefinery.github.io/documentation/gh_workflow/
name: Deploy Sphinx documentation to GitHub Pages

on:  # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        # This is the version of the action for setting up Python,
        # not the Python version.
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: Install Sphinx
        run: |
          python -m pip install -U sphinx
          python -m pip install furo
          python -m pip install docutils
          python -m pip install --upgrade myst-parser
          python -m pip install commonmark
          python -m pip install docutils
      - name: Check Sphinx version
        run: |
          sphinx-build --version
          sphinx-quickstart --version
      - name: Check whether MyST parser is available
        run:
          python -c "import myst_parser"
      - name: Sphinx Build
        run: |
          sphinx-build docs docs/_build --verbose
      - name: Sphinx Linkcheck
        run: |
      #    sphinx-build -b linkcheck docs docs/_build/linkcheck
        continue-on-error: true
      - name: Documentation Coverage
        run: |
       #   sphinx-build -b coverage docs docs/_build/coverage
      - name: Fix broken links for Sphinx docs
        run: |
          echo "Not implemented"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/
          force_orphan: false
          keep_files: false
