name: Lint, Test & CodeQL Pipeline

on:
  push:
    branches:
      - master

jobs:
  markdown-lint:
    name: Markdown Lint
    uses: ikostan/pico/.github/workflows/markdown-lint.yml@master
  flake8:
    name: Lint with flake8
    uses: ikostan/pico/.github/workflows/flake8.yml@master
  pylint:
    name: Lint with pylint
    uses: ikostan/pico/.github/workflows/pylint.yml@master
  mypy:
    name: Python Data Type Checking
    uses: ikostan/pico/.github/workflows/mypy.yml@master
  pytest:
    name: Unitest with pytest
    needs:
      - flake8
      - pylint
      - markdown-lint
      - mypy
    uses: ikostan/pico/.github/workflows/pytest.yml@master
  codecov:
    name: Codecov GitHub Action
    needs:
      - pytest
    uses: ikostan/pico/.github/workflows/codecov.yml@master
    # Why is Codecov upload step in GitHub Actions not finding the token?
    # https://stackoverflow.com/questions/78298827/why-is-codecov-upload-step-in-github-actions-not-finding-the-token
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  codeql:
    name: CodeQL for a new build
    needs:
      - pytest
      - codecov
    uses: ikostan/pico/.github/workflows/codeql_build.yml@master
