name: Lint, Test & CodeQL Pipeline

on:
  push:
    branches:
      - master

jobs:
  flake8:
    name: Lint with flake8
    uses: ikostan/pico/.github/workflows/flake8.yml@master
  pylint:
    name: Lint with pylint
    uses: ikostan/pico/.github/workflows/pylint.yml@master
  pytest:
    name: Unitest with pytest
    needs:
      - flake8
      - pylint
    uses: ikostan/pico/.github/workflows/pytest.yml@master
  codeql:
    name: CodeQL for a new build
    needs:
      - pytest
    uses: ikostan/pico/.github/workflows/codeql_build.yml@master
